"""
Shared constants and paths used across all pipeline scripts.
=============================================================
Imported by: eda.py, build_features.py, modelling.py, evaluation.py
"""

from pathlib import Path
import pandas as pd

SRC_DIR = Path(__file__).resolve().parent
IO_DIR  = SRC_DIR / "io"
IO_DIR.mkdir(exist_ok=True)

MASTER_PATH    = IO_DIR / "master.csv"
LABELLED_PATH  = IO_DIR / "master_labelled.csv"

RAW_FILES = {
    "Alarms":            IO_DIR / "ALLARMI.csv",
    "Traveler_type":     IO_DIR / "TIPOLOGIA_VIAGGIATORE.csv",
}

SNAPSHOT_DATE = pd.Timestamp("2025-03-01")

NAVY  = "#1A3764"
STEEL = "#4682B4"
CORAL = "#E8735A"
GREEN = "#27AE60"
PALETTE = [NAVY, STEEL, CORAL, GREEN, "#F4A261", "#2A9D8F", "#E76F51"]

manual_mapping = {
    "OCCORRENZE": "occurrences",
    "AREOPORTO_ARRIVO": "arrival_airport_iata",
    "AREOPORTO_PARTENZA": "departure_airport_iata",
    "ANNO_PARTENZA": "departure_year",
    "MESE_PARTENZA": "departure_month",
    "DATA_PARTENZA": "departure_date",
    "DESCR_AEREOPORTO_ARR": "arrival_airport_description",
    "DESCR_AEREOPORTO_PART": "departure_airport_description",
    "CITTA_ARR": "arrival_city",
    "CITTA_PARTENZA": "departure_city",
    "CODICE_PAESE_ARR": "arrival_country_code",
    "CODICE_PAESE_PART": "departure_country_code",
    "PAESE_ARR": "arrival_country",
    "PAESE_PART": "departure_country",
    "ZONA": "zone",
    "TOT": "total",
    "MOTIVO_ALLARME": "alarm_reason",
    "note_operatore": "operator_notes",
    "flag_rischio": "risk_flag",
    "Paese Partenza": "departure_country_full",
    "CODICE PAESE ARR": "arrival_country_code_full",
    "3zona": "zone_3",
    "paese%arr": "arrival_country_percentage",
    "tot voli": "total_flights",
    "NAZIONALITA": "nationality",
    "GIORNO_PARTENZA": "departure_day",
    "ENTRATI": "entries",
    "INVESTIGATI": "investigated",
    "ALLARMATI": "alarms",
    "TIPO_DOCUMENTO": "document_type",
    "GENERE": "gender",
    "FASCIA_ETA": "age_group",
    "FLAG_TRANSITO": "transit_flag",
    "COMPAGNIA_AEREA": "airline",
    "NUMERO_VOLO": "flight_number",
    "ESITO_CONTROLLO": "control_outcome",
    "codice_rischio": "risk_code",
    "Tipo_Documento": "document_type2",
    "FASCIA_ETA2": "age_group2",
    "3nazionalita": "nationality_3",
    "compagnia%aerea": "airline%",
    "num volo": "flight number"
}
it_to_en = {
    'Albania': 'Albania',
    'Algeria': 'Algeria',
    'Antigua e barbuda': 'Antigua and Barbuda',
    'Arabia saudita': 'Saudi Arabia',
    'Argentina': 'Argentina',
    'Armenia': 'Armenia',
    'Azerbaigian': 'Azerbaijan',
    'Bahrain': 'Bahrain',
    'Brasile': 'Brazil',
    'Canada': 'Canada',
    'Capo verde': 'Cabo Verde',
    'Cina': 'China',
    'Corea del sud': 'Korea, Republic of',
    'Cossovo': 'Kosovo',
    'Egitto': 'Egypt',
    'Emirati arabi uniti': 'United Arab Emirates',
    'Etiopia': 'Ethiopia',
    'Georgia': 'Georgia',
    'Giamaica': 'Jamaica',
    'Giappone': 'Japan',
    'Giordania': 'Jordan',
    'Hong kong': 'Hong Kong',
    'India': 'India',
    'Iran': 'Iran, Islamic Republic of',
    'Israele': 'Israel',
    'Kazakistan': 'Kazakhstan',
    'Kenya': 'Kenya',
    'Kuwait': 'Kuwait',
    'Libano': 'Lebanon',
    'Libia': 'Libya',
    'Macedonia': 'North Macedonia',
    'Maldive': 'Maldives',
    'Marocco': 'Morocco',
    'Mauritius': 'Mauritius',
    'Messico': 'Mexico',
    'Moldavia': 'Moldova, Republic of',
    'Montenegro': 'Montenegro',
    'Oman': 'Oman',
    'Qatar': 'Qatar',
    'Regno unito': 'United Kingdom',
    'Repubblica dominicana': 'Dominican Republic',
    'Senegal': 'Senegal',
    'Serbia': 'Serbia',
    'Singapore': 'Singapore',
    'Stati uniti': 'United States',
    'Taiwan': 'Taiwan, Province of China',
    'Tanzania': 'Tanzania, United Republic of',
    'Tunisia': 'Tunisia',
    'Turchia': 'Turkey',
    'Uzbekistan': 'Uzbekistan'
}
city_mapping = {
    'Algeri': 'Algiers',
    'Belgrado': 'Belgrade',
    'Citta Del Messico': 'Mexico City',
    'Filadelfia': 'Philadelphia',
    'Londra': 'London',
    'Nuova Delhi': 'New Delhi',
    'Pechino': 'Beijing',
    'San Paolo': 'Sao Paulo',
    'Skopie': 'Skopje',
    'Smirne': 'Izmir',
    'Tel Aviv Yafo': 'Tel Aviv',
    'St. John\'S': "St. John's",
    'Buenos Aires': 'Buenos Aires',
    'Rio De Janeiro': 'Rio de Janeiro',
    'Abu Dhabi': 'Abu Dhabi',
    'Addis Ababa': 'Addis Ababa',
    'Hong Kong': 'Hong Kong',
    'Kuwait City': 'Kuwait City',
    'Los Angeles': 'Los Angeles',
    'New York': 'New York'
}
iata_mapping = {
    'AUH': {'city': 'Abu Dhabi', 'airport': 'Abu Dhabi International'},
    'ADD': {'city': 'Addis Ababa', 'airport': 'Bole International'},
    'AGA': {'city': 'Agadir', 'airport': 'Agadir Al Massira'},
    'ALG': {'city': 'Algiers', 'airport': 'Houari Boumediene'},
    'ALA': {'city': 'Almaty', 'airport': 'Almaty International'},
    'AMM': {'city': 'Amman', 'airport': 'Queen Alia International'},
    'ANU': {'city': "St. John's", 'airport': 'V.C. Bird International'},
    'ATL': {'city': 'Atlanta', 'airport': 'Hartsfield-Jackson Atlanta International'},
    'ATQ': {'city': 'Amritsar', 'airport': 'Sri Guru Ram Dass Jee International'},
    'BAH': {'city': 'Manama', 'airport': 'Bahrain International'},
    'BEG': {'city': 'Belgrade', 'airport': 'Nikola Tesla'},
    'BEY': {'city': 'Beirut', 'airport': 'Beirut-Rafic Hariri International'},
    'BFS': {'city': 'Belfast', 'airport': 'Belfast International'},
    'BHX': {'city': 'Birmingham', 'airport': 'Birmingham International'},
    'BOS': {'city': 'Boston', 'airport': 'Logan International'},
    'BRS': {'city': 'Bristol', 'airport': 'Bristol Airport'},
    'CAI': {'city': 'Cairo', 'airport': 'Cairo International'},
    'CAN': {'city': 'Guangzhou', 'airport': 'Guangzhou Baiyun International'},
    'CGO': {'city': 'Zhengzhou', 'airport': 'Zhengzhou Xinzheng International'},
    'CKG': {'city': 'Chongqing', 'airport': 'Chongqing Jiangbei International'},
    'CMN': {'city': 'Casablanca', 'airport': 'Mohammed V International'},
    'CUN': {'city': 'Cancun', 'airport': 'Cancun International'},
    'DEL': {'city': 'New Delhi', 'airport': 'Indira Gandhi International'},
    'DFW': {'city': 'Dallas-Fort Worth', 'airport': 'Dallas/Fort Worth International'},
    'DMM': {'city': 'Dammam', 'airport': 'King Fahd International'},
    'DOH': {'city': 'Doha', 'airport': 'Hamad International'},
    'DSS': {'city': 'Dakar', 'airport': 'Blaise Diagne International'},
    'DWC': {'city': 'Dubai', 'airport': 'Al Maktoum International'},
    'DXB': {'city': 'Dubai', 'airport': 'Dubai International'},
    'EDI': {'city': 'Edinburgh', 'airport': 'Edinburgh Airport'},
    'EVN': {'city': 'Yerevan', 'airport': 'Zvartnots International'},
    'EWR': {'city': 'Newark', 'airport': 'Newark Liberty International'},
    'EZE': {'city': 'Buenos Aires', 'airport': 'Ezeiza Ministro Pistarini'},
    'FAB': {'city': 'Farnborough', 'airport': 'Farnborough Airport'},
    'FEZ': {'city': 'Fes', 'airport': 'Fes-Saiss'},
    'GIG': {'city': 'Rio de Janeiro', 'airport': 'Galeao-Antonio Carlos Jobim International'},
    'GLA': {'city': 'Glasgow', 'airport': 'Glasgow International'},
    'GRU': {'city': 'Sao Paulo', 'airport': 'Sao Paulo/Guarulhos International'},
    'GYD': {'city': 'Baku', 'airport': 'Heydar Aliyev International'},
    'HGH': {'city': 'Hangzhou', 'airport': 'Hangzhou Xiaoshan International'},
    'HKG': {'city': 'Hong Kong', 'airport': 'Hong Kong International'},
    'HND': {'city': 'Tokyo', 'airport': 'Tokyo Haneda International'},
    'HRG': {'city': 'Hurghada', 'airport': 'Hurghada International'},
    'IAD': {'city': 'Washington', 'airport': 'Washington Dulles International'},
    'ICN': {'city': 'Seoul', 'airport': 'Incheon International'},
    'IKA': {'city': 'Tehran', 'airport': 'Imam Khomeini International'},
    'IST': {'city': 'Istanbul', 'airport': 'Istanbul Airport'},
    'JED': {'city': 'Jeddah', 'airport': 'King Abdulaziz International'},
    'JFK': {'city': 'New York', 'airport': 'John F. Kennedy International'},
    'KIV': {'city': 'Chisinau', 'airport': 'Chisinau International'},
    'KUT': {'city': 'Kutaisi', 'airport': 'Kutaisi International'},
    'KWI': {'city': 'Kuwait City', 'airport': 'Kuwait International'},
    'LAX': {'city': 'Los Angeles', 'airport': 'Los Angeles International'},
    'LBA': {'city': 'Leeds', 'airport': 'Leeds Bradford'},
    'LCY': {'city': 'London', 'airport': 'London City'},
    'LGW': {'city': 'London', 'airport': 'London Gatwick'},
    'LHR': {'city': 'London', 'airport': 'London Heathrow'},
    'LPL': {'city': 'Liverpool', 'airport': 'Liverpool John Lennon'},
    'LRM': {'city': 'La Romana', 'airport': 'La Romana International'},
    'LTN': {'city': 'London', 'airport': 'London Luton'},
    'LXR': {'city': 'Luxor', 'airport': 'Luxor International'},
    'MAN': {'city': 'Manchester', 'airport': 'Manchester Airport'},
    'MBA': {'city': 'Mombasa', 'airport': 'Moi International'},
    'MBJ': {'city': 'Montego Bay', 'airport': 'Sangster International'},
    'MCT': {'city': 'Muscat', 'airport': 'Muscat International'},
    'MEX': {'city': 'Mexico City', 'airport': 'Benito Juarez International'},
    'MIA': {'city': 'Miami', 'airport': 'Miami International'},
    'MLE': {'city': 'Male', 'airport': 'Velana International'},
    'MRU': {'city': 'Plaisance', 'airport': 'Sir Seewoosagur Ramgoolam International'},
    'NCL': {'city': 'Newcastle', 'airport': 'Newcastle Airport'},
    'NKG': {'city': 'Nanjing', 'airport': 'Nanjing Lukou International'},
    'OAK': {'city': 'Oakland', 'airport': 'Oakland International'},
    'OXF': {'city': 'Oxford', 'airport': 'London Oxford'},
    'PEK': {'city': 'Beijing', 'airport': 'Beijing Capital International'},
    'PHL': {'city': 'Philadelphia', 'airport': 'Philadelphia International'},
    'PRN': {'city': 'Pristina', 'airport': 'Prishtina International'},
    'PVG': {'city': 'Shanghai', 'airport': 'Shanghai Pudong International'},
    'RAK': {'city': 'Marrakech', 'airport': 'Menara'},
    'RBA': {'city': 'Rabat', 'airport': 'Rabat-Sale'},
    'RMO': {'city': 'Chisinau', 'airport': 'Chisinau International'},
    'RUH': {'city': 'Riyadh', 'airport': 'King Khaled International'},
    'SAW': {'city': 'Istanbul', 'airport': 'Sabiha Gokcen'},
    'SHJ': {'city': 'Sharjah', 'airport': 'Sharjah International'},
    'SID': {'city': 'Sal', 'airport': 'Amilcar Cabral International'},
    'SIN': {'city': 'Singapore', 'airport': 'Changi'},
    'SKP': {'city': 'Skopje', 'airport': 'Skopje International'},
    'SLL': {'city': 'Salalah', 'airport': 'Salalah Airport'},
    'SSH': {'city': 'Sharm El Sheikh', 'airport': 'Sharm El-Sheikh International'},
    'STN': {'city': 'London', 'airport': 'London Stansted'},
    'SZX': {'city': 'Shenzhen', 'airport': 'Shenzhen Baoan International'},
    'TAS': {'city': 'Tashkent', 'airport': 'Tashkent International'},
    'TBS': {'city': 'Tbilisi', 'airport': 'Tbilisi International'},
    'TGD': {'city': 'Podgorica', 'airport': 'Podgorica Airport'},
    'TIA': {'city': 'Tirana', 'airport': 'Rinas Mother Teresa'},
    'TLV': {'city': 'Tel Aviv', 'airport': 'Ben Gurion International'},
    'TNG': {'city': 'Tangier', 'airport': 'Ibn Battouta'},
    'TPE': {'city': 'Taipei', 'airport': 'Taiwan Taoyuan International'},
    'TUN': {'city': 'Tunis', 'airport': 'Tunis-Carthage'},
    'WNZ': {'city': 'Wenzhou', 'airport': 'Wenzhou Longwan International'},
    'YUL': {'city': 'Montreal', 'airport': 'Montreal-Trudeau International'},
    'YYZ': {'city': 'Toronto', 'airport': 'Toronto Pearson International'},
    'ZNZ': {'city': 'Zanzibar', 'airport': 'Abeid Amani Karume International'}
}